# -*- coding: utf-8 -*-
"""App-kltn-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4iRwqZRq7fT_djE1lXeBHf0kw8ykqJZ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile financial_report_app.py
# !pip install -q streamlit
# !npm install localtunnel
# import streamlit as st
# import pandas as pd
# import joblib
# import numpy as np
# # ===== 1. Load mô hình Random Forest và scaler =====
# model = joblib.load("bankruptcy_model_RF_1 (1).pkl")
# scaler = joblib.load("scaler (1).pkl")
# 
# # ===== 2. Cấu hình giao diện =====
# st.set_page_config(page_title="Dự báo phá sản doanh nghiệp xây dựng", layout="centered")
# st.title("🏗️ DỰ BÁO RỦI RO PHÁ SẢN DOANH NGHIỆP XÂY DỰNG")
# st.markdown("Ứng dụng kết hợp mô hình học máy Random Forest và mô hình Z’’-score mở rộng.")
# 
# st.header("📥 Nhập thông tin tài chính doanh nghiệp")
# 
# # ===== 3. Nhập dữ liệu người dùng =====
# X1 = st.number_input("X1: Vốn lưu động / Tổng tài sản", value=0.0, format="%.4f")
# X2 = st.number_input("X2: Lợi nhuận giữ lại / Tổng tài sản", value=0.0, format="%.4f")
# X3 = st.number_input("X3: EBIT / Tổng tài sản", value=0.0, format="%.4f")
# X4 = st.number_input("X4: Vốn chủ sở hữu / Tổng nợ phải trả", value=0.0, format="%.4f")
# X5 = st.number_input("X5: Tổng nợ phải trả / Tổng tài sản", value=0.0, format="%.4f")
# X6 = st.number_input("X6: Tỷ suất sinh lời trên tổng tài sản (ROA)", value=0.0, format="%.2f")
# 
# # ===== 4. Nút dự báo =====
# if st.button("📊 Thực hiện dự báo"):
# 
#     # Dự đoán bằng mô hình học máy (Random Forest)
#     input_df = pd.DataFrame([[X1, X2, X3, X4, X5, X6]], columns=['X1', 'X2', 'X3', 'X4', 'X5', 'X6'])
#     scaled_input = scaler.transform(input_df)
#     rf_pred = model.predict(scaled_input)[0]
#     rf_proba = model.predict_proba(scaled_input)[0]
# 
#     # Dự đoán bằng mô hình Z’’-score (giả định hệ số)
#     # Hệ số tham khảo từ mô hình Z’’ dành cho doanh nghiệp phi sản xuất (không có X5)
#     z_score = 6.56*X1 + 3.26*X2 + 6.72*X3 + 1.05*X4
# 
#     # Phân loại theo Z’’
#     if z_score < 1.1:
#         z_risk = "❌ Rủi ro cao"
#     elif z_score < 2.6:
#         z_risk = "⚠️ Cảnh báo"
#     else:
#         z_risk = "✅ An toàn"
# 
#     # Phân loại Random Forest
#     rf_label_map = {
#         0: "✅ An toàn",
#         1: "⚠️ Cảnh báo",
#         2: "❌ Rủi ro cao"
#     }
# 
#     # ===== 5. Hiển thị kết quả =====
#     st.success("🎯 Dự báo hoàn tất")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.subheader("🤖 Mô hình Random Forest")
#         st.write("**Phân loại:**", rf_label_map[rf_pred])
#         st.write("**Xác suất:**")
#         st.write(f"- An toàn (0): {rf_proba[0]*100:.2f}%")
#         st.write(f"- Cảnh báo (1): {rf_proba[1]*100:.2f}%")
#         st.write(f"- Rủi ro cao (2): {rf_proba[2]*100:.2f}%")
# 
#     with col2:
#         st.subheader("📐 Mô hình Z’’-score truyền thống")
#         st.write("**Z’’-score:**", f"{z_score:.4f}")
#         st.write("**Phân loại:**", z_risk)
# 
#     # ===== 6. So sánh kết quả =====
#     st.markdown("---")
#     st.subheader("🔍 So sánh hai mô hình")
# 
#     if rf_label_map[rf_pred] == z_risk:
#         st.success("✅ Hai mô hình đồng thuận về rủi ro.")
#     else:
#         st.warning("⚠️ Có sự khác biệt giữa dự đoán của Random Forest và Z’’-score.")
# 
#     st.markdown("**Ghi chú:** Mô hình Z’’ sử dụng 4 biến tài chính; Random Forest sử dụng 6 biến nên có thể cho kết quả khác nhau trong một số trường hợp.")
# 
#     # ===== 7. Xuất bảng tổng hợp =====
#     st.markdown("### 🧾 Tổng hợp chỉ số tài chính")
#     st.dataframe(pd.DataFrame([{
#         "X1": X1, "X2": X2, "X3": X3,
#         "X4": X4, "X5": X5, "X6": X6,
#         "Z’’-score": round(z_score, 4),
#         "ML_Prediction": rf_label_map[rf_pred]
#     }]))
#

# !npm install -g localtunnel

# !streamlit run financial_report_app.py &>/dev/null &

# import urllib
# print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))
# !npx localtunnel --port 8501